USE [master]
GO

/****** Object:  Database [lib]    Script Date: 4/20/2023 4:04:47 PM ******/
CREATE DATABASE [lib]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lib', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\lib.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'lib_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\lib_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lib].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lib] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lib] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lib] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lib] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lib] SET ARITHABORT OFF 
GO

ALTER DATABASE [lib] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lib] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lib] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lib] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lib] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lib] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lib] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lib] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lib] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lib] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lib] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lib] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lib] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lib] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lib] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lib] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lib] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lib] SET RECOVERY FULL 
GO

ALTER DATABASE [lib] SET  MULTI_USER 
GO

ALTER DATABASE [lib] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lib] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lib] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lib] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [lib] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lib] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [lib] SET QUERY_STORE = OFF
GO

ALTER DATABASE [lib] SET  READ_WRITE 
GO

